# Generated by Django 4.2.5 on 2023-11-08 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 9, 52, 38, 997637)),
        ),
    ]
