# Generated by Django 4.2.5 on 2023-11-22 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_students_slug_alter_students_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 9, 20, 19, 274269)),
        ),
    ]
